# Generated by Django 5.0.6 on 2024-07-14 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaJuego',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='categoriaSerie',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='desarrollador',
            fields=[
                ('idDev', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='nivelEducacional',
            fields=[
                ('idEducacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='tipoClave',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idJuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=550)),
                ('imagen', models.ImageField(upload_to='juegos/imagenes')),
                ('ytVidId', models.CharField(max_length=11, null=True)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('clave', models.FileField(upload_to='juegos/archivos_zip/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.categoriajuego')),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.desarrollador')),
                ('tipoClave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.tipoclave')),
            ],
        ),
        migrations.CreateModel(
            name='imgJuegos',
            fields=[
                ('idImg', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='juegos/capturas')),
                ('idJuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('idSerie', models.IntegerField(primary_key=True, serialize=False)),
                ('estudio', models.CharField(max_length=50, null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=220)),
                ('fechalanz', models.DateField(default='2000-01-01')),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='series/imagenes')),
                ('stock', models.IntegerField()),
                ('clave', models.FileField(upload_to='series/claves_zip/')),
                ('ytVidId', models.CharField(max_length=11, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.categoriaserie')),
            ],
        ),
        migrations.CreateModel(
            name='imagenSerie',
            fields=[
                ('idImagen', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='series/imagenes/')),
                ('idSerie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarro', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('juegos', models.ManyToManyField(blank=True, related_name='carritos', to='Store.juego')),
                ('series', models.ManyToManyField(blank=True, related_name='carritos', to='Store.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('rut', models.CharField(default='11111111-1', max_length=40)),
                ('email', models.EmailField(max_length=70)),
                ('telefono', models.CharField(max_length=40)),
                ('fechaNac', models.DateField(default='2000-01-01')),
                ('nivelEd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.niveleducacional')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.region')),
            ],
        ),
    ]
