# Generated by Django 5.0.6 on 2024-07-16 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dispHab',
            fields=[
                ('idDisp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='nivelEducacional',
            fields=[
                ('idEducacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('idServ', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoHab',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idHab', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=550)),
                ('imagen', models.ImageField(upload_to='habitaciones/imagenes')),
                ('ytVidId', models.CharField(max_length=11, null=True)),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('dispHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.disphab')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.servicio')),
                ('tipoHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.tipohab')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarro', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ManyToManyField(blank=True, related_name='carritos', to='Store.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='imgHab',
            fields=[
                ('idImg', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='habitaciones/capturas')),
                ('idHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.IntegerField(primary_key=True, serialize=False)),
                ('dias', models.CharField(max_length=50, null=True)),
                ('fecha', models.DateField(default='2000-01-01')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('rut', models.CharField(default='11111111-1', max_length=40)),
                ('email', models.EmailField(max_length=70)),
                ('telefono', models.CharField(max_length=40)),
                ('fechaNac', models.DateField(default='2000-01-01')),
                ('nivelEd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.niveleducacional')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.region')),
            ],
        ),
    ]
