# Generated by Django 5.0.6 on 2024-07-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='idUsuario',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='Store.usuario'),
        ),
    ]
