# Generated by Django 5.0.6 on 2024-07-16 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='desarrollador',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='tipoClave',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='juegos',
        ),
        migrations.RenameModel(
            old_name='categoriaJuego',
            new_name='dispHab',
        ),
        migrations.RenameModel(
            old_name='desarrollador',
            new_name='servicio',
        ),
        migrations.RenameModel(
            old_name='tipoClave',
            new_name='tipoHab',
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idHab', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=550)),
                ('imagen', models.ImageField(upload_to='juegos/imagenes')),
                ('ytVidId', models.CharField(max_length=11, null=True)),
                ('precio', models.IntegerField()),
                ('capacidad', models.IntegerField()),
                ('dispHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.disphab')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.servicio')),
                ('tipoHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.tipohab')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='reserva',
            field=models.ManyToManyField(blank=True, related_name='carritos', to='Store.habitacion'),
        ),
        migrations.CreateModel(
            name='imgHab',
            fields=[
                ('idImg', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='juegos/capturas')),
                ('idHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.habitacion')),
            ],
        ),
        migrations.DeleteModel(
            name='imgJuegos',
        ),
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
