# Generated by Django 5.0.6 on 2024-07-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='idReserva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
