# Generated by Django 5.0.6 on 2024-07-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_reserva_idreserva'),
        ('Store', '0002_reserva_idusuario'),
    ]

    operations = [
    ]
