# Generated by Django 5.0.6 on 2024-07-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_remove_juego_categoria_remove_juego_desarrollador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriaserie',
            old_name='idCategoria',
            new_name='idDisp',
        ),
        migrations.RenameField(
            model_name='disphab',
            old_name='idCategoria',
            new_name='idDisp',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='idDev',
            new_name='idServ',
        ),
    ]
