# Generated by Django 5.0.6 on 2024-07-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_merge_20240716_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='idReserva',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
